language: go
sudo: false

go:
    - '1.9'
    - '1.10'
    - '1.11'

install:
    - go get -u golang.org/x/lint/golint
    - go get -u github.com/GeertJohan/fgt

script:
    - make && make check
    - fgt gofmt -l $(find src -name \*.go)
    - fgt find src -type d -exec golint {} \;
